[package]
cairo-version = "2.8.4"
name = "clash_prototype"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.12" }
starknet = "2.8.4"

[dev-dependencies]
cairo_test = "2.8.4"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.12" }

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[features]
default = []

[profile.dev]
[profile.sepolia]
